<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Disney Princesses</title>
    <link rel="icon" href="/images/logos/disney-letter-logo.png" type="image/png">

    <!-- BOOTSTRAP -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>
        
    <!-- FONTS -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Dosis:wght@200..800&family=Emilys+Candy&family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Patrick+Hand+SC&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <!-- STYLE SHEET-->

    <link rel="stylesheet" href="/style.css">

</head>

<body>

    <!-- NAVIGATION BAR -->

    <nav class="navbar navbar-expand-lg navbar-custom">

        <div class="container-fluid">

            <!-- HEADER LOGO -->

            <a class="navbar-brand" href="index.html">
                <img src="/images/logos/disney-logo.png" alt="Logo" width="60" height="24"
                    class="d-inline-block align-text-top">
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <!-- HOME BUTTON -->

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="index.html">Home</a>
                    </li>

                    <!-- DETAILS BUTTON -->

                    <li class="nav-item">
                        <a class="nav-link" href="details.html">Details</a>
                    </li>

                    <!-- ABOUT BUTTON -->

                    <li class="nav-item">
                        <a class="nav-link" href="about.html">About</a>
                    </li>

                    <!-- ADD A CHARACTER -->

                    <li class="nav-item">
                        <a class="nav-link" href="new-character-form.html">Add a Character!</a>
                    </li>

                </ul>

                <!-- SEARCH BAR -->

                <form class="d-flex" role="search">

                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                    <button class="btn btn-outline-custom" type="submit">Search</button>

                </form>

            </div>

        </div>

    </nav>

    <!-- WRITTEN DETAILS -->

    <div class="container-fluid">

        <div class="my-4 text-center">
            <img src="images/logos/disney-princess-logo.png" alt="Logo" width="200" height="90">
        </div>

        <h1 class="mx-4">Welcome to our Enchanted Kingdom!</h1>

        <h5 class="body-text m-4">
            We believe that every day deserves a touch of magic and a sprinkle of stardust. 
            This is a digital sanctuary dedicated to the dreamers, the brave, and the kind-hearted— all the Disney Princesses (and princesses-at-heart) who inspire us to follow our dreams.

        </h5>

        <h4 class="m-4">Our Fairytale</h4>

        <h5 class="body-text m-4">
            Our mission is to celebrate the timeless stories and empowering legacies of the royalty we grew up with.
            From Cinderella’s unwavering hope to Moana’s courageous spirit, we dive deep into the lore, style, and magic that make these characters icons. 
            Whether you’re looking for princess character guides or just a dose of nostalgia, you’ve found your home.
        </h5>

        <h4 class="m-4">What You'll Find Here</h4>

        <h5 class="body-text m-4">
            
            <ul>
                <li>Royal Biographies: Get to know the origins and adventures of your favorites.</li>
                <li>Whimsical Style: Inspiration for "Disney-bounding" and princess-inspired aesthetics.</li>
                <li>Empowerment: Celebrating the strength and kindness that define modern royalty.</li>
            </ul>

            <br>
                            
            Life isn't always a fairytale, but we’re here to make sure yours feels a little more like one. Put on your
            crown, grab your sidekick, and let’s make some magic together!

        </h5>

    </div>

</body>

</html>